apiVersion: v1
kind: Service
metadata:
  name: cloths-classifier-service
spec:
  type: NodePort
  selector:
    app: cloths-classifier
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
