apiVersion: v1
kind: Service
metadata:
  name: churn-prediction-service
spec:
  type: NodePort
  selector:
    app: churn-prediction
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30009